blocked-entities:
    - EXPERIENCE_ORB
    - WITHER_SKULL
    - WITHER
    - BAT
    - WITCH
    - ENDERMAN
    - CAVE_SPIDER
    - SILVERFISH
    - BLAZE
    - SNOWMAN
    - OCELOT
    - IRON_GOLEM
    - VILLAGER
    - HORSE
    - ENDER_CRYSTAL
    - MAGMA_CUBE

blocked-items:
    - 116
    - 117
    - 118
    - 120
    - 129
    - 130
    - 133
    - 138
    - 170
    - 172
    - 173
    - 357
    - 358
    - 359
    - 361
    - 362
    - 368
    - 369
    - 370
    - 372
    - 373
    - 374
    - 375
    - 376
    - 378
    - 379
    - 380
    - 381
    - 383
    - 384
    - 388
    - 391
    - 392
    - 393
    - 394
    - 396
    - 397
    - 399
    - 400
    - 401
    - 402
    - 405
    - 406
    - 417
    - 418
    - 419
    - 420
    - 421